/*
  Copyright (c), 2001-2022, Shenshu Tech. Co., Ltd.
 */

#ifndef __HI_COMMON_OTP_H__
#define __HI_COMMON_OTP_H__

#include "hi_type.h"
#include "ot_common_otp.h"

#ifdef __cplusplus
extern "C" {
#endif

#define HI_ERR_OTP_NOT_INIT OT_ERR_OTP_NOT_INIT
#define HI_ERR_OTP_NULL_PTR OT_ERR_OTP_NULL_PTR
#define HI_ERR_OTP_BUSY OT_ERR_OTP_BUSY
#define HI_ERR_OTP_FAILED_INIT OT_ERR_OTP_FAILED_INIT
#define HI_ERR_OTP_FAILED_MEM OT_ERR_OTP_FAILED_MEM
#define HI_ERR_OTP_FAILED_SEC_FUNC OT_ERR_OTP_FAILED_SEC_FUNC
#define HI_ERR_OTP_INVALID_PARAM OT_ERR_OTP_INVALID_PARAM
#define HI_ERR_OTP_INVALID_FIELD_NAME OT_ERR_OTP_INVALID_FIELD_NAME
#define HI_ERR_OTP_ZONE_ALREADY_SET OT_ERR_OTP_ZONE_ALREADY_SET
#define HI_ERR_OTP_ZONE_LOCKED OT_ERR_OTP_ZONE_LOCKED
#define HI_ERR_OTP_ZONE_NO_PERMIT OT_ERR_OTP_ZONE_NO_PERMIT
#define HI_ERR_OTP_WAIT_TIMEOUT OT_ERR_OTP_WAIT_TIMEOUT
#define HI_ERR_OTP_FUNC_UNSUPPORT OT_ERR_OTP_FUNC_UNSUPPORT
#define HI_OTP_PV_NAME_MAX_LEN OT_OTP_PV_NAME_MAX_LEN
#define HI_OTP_PV_VALUE_MAX_LEN OT_OTP_PV_VALUE_MAX_LEN
typedef ot_otp_burn_pv_item hi_otp_burn_pv_item;
#define HI_OTP_STA_ALL_UNLOCKED OT_OTP_STA_ALL_UNLOCKED
#define HI_OTP_STA_PARTIAL_LOCKED OT_OTP_STA_PARTIAL_LOCKED
#define HI_OTP_STA_ALL_LOCKED OT_OTP_STA_ALL_LOCKED
#define HI_OTP_STA_BUTT OT_OTP_STA_BUTT
typedef ot_otp_lock_status hi_otp_lock_status;

#ifdef __cplusplus
}
#endif

#endif /* __HI_COMMON_OTP_H__ */
