/*
  Copyright (c), 2001-2022, Shenshu Tech. Co., Ltd.
 */

#ifndef __HI_COMMON_MCF_CALIBRATION_H__
#define __HI_COMMON_MCF_CALIBRATION_H__

#include "hi_type.h"
#include "hi_common_video.h"
#include "hi_errno.h"
#include "ot_common_mcf_calibration.h"

#ifdef __cplusplus
extern "C" {
#endif

#define HI_ERR_CALIB_FEATURE_OVERFLOW OT_ERR_CALIB_FEATURE_OVERFLOW
#define HI_ERR_CALIB_FEATURE_LACK OT_ERR_CALIB_FEATURE_LACK
#define HI_ERR_CALIB_RANSAC_FAIL OT_ERR_CALIB_RANSAC_FAIL
#define HI_ERR_CALIB_ILLEGAL_MATRIX OT_ERR_CALIB_ILLEGAL_MATRIX
#define HI_ERR_CALIB_ILLEGAL_MOTION OT_ERR_CALIB_ILLEGAL_MOTION
#define HI_ERR_CALIB_FAIL OT_ERR_CALIB_FAIL
#define HI_ERR_MCF_CALIBRATION_NULL_PTR OT_ERR_MCF_CALIBRATION_NULL_PTR
#define HI_ERR_MCF_CALIB_FEATURE_OVERFLOW OT_ERR_MCF_CALIB_FEATURE_OVERFLOW
#define HI_ERR_MCF_CALIB_FEATURE_LACK OT_ERR_MCF_CALIB_FEATURE_LACK
#define HI_ERR_MCF_CALIB_RANSAC_FAIL OT_ERR_MCF_CALIB_RANSAC_FAIL
#define HI_ERR_MCF_CALIB_ILLEGAL_MATRIX OT_ERR_MCF_CALIB_ILLEGAL_MATRIX
#define HI_ERR_MCF_CALIB_ILLEGAL_MOTION OT_ERR_MCF_CALIB_ILLEGAL_MOTION
#define HI_ERR_MCF_CALIB_FAIL OT_ERR_MCF_CALIB_FAIL
#define HI_ERR_MCF_CALIBRATION_ILLEGAL_PARAM OT_ERR_MCF_CALIBRATION_ILLEGAL_PARAM
#define HI_ERR_MCF_CALIBRATION_NOMEM OT_ERR_MCF_CALIBRATION_NOMEM
#define HI_MCF_COEF_NUM OT_MCF_COEF_NUM
#define HI_MCF_CALIBRATION_AFFINE OT_MCF_CALIBRATION_AFFINE
#define HI_MCF_CALIBRATION_PROJECTIVE OT_MCF_CALIBRATION_PROJECTIVE
#define HI_MCF_CALIBRATION_MODE_BUTT OT_MCF_CALIBRATION_MODE_BUTT
typedef ot_mcf_calibration_mode hi_mcf_calibration_mode;
typedef ot_mcf_calibration hi_mcf_calibration;
typedef ot_mcf_feature_info hi_mcf_feature_info;

#ifdef __cplusplus
}
#endif
#endif /* __HI_COMMON_MCF_CALIBRATION_H__ */
