# Hisilicon Hi35xx uvc camera sample Makefile

include ../Makefile.param

include $(PWD)/Makefile.$(OSTYPE).param

TARGET := uvc_app
TARGET_PATH := $(PWD)

# compile linux or HuaweiLite
include $(PWD)/../$(ARM_ARCH)_$(OSTYPE).mak
