/*
  Copyright (c), 2001-2024, Shenshu Tech. Co., Ltd.
 */
#ifndef __AUTOCONF_H__
#define __AUTOCONF_H__

#define AUTOCONF_TIMESTAMP "2024-01-25 09:30:09 CST"

/*
 * General Setup
 */
#define CONFIG_HI3519DV500 1
#define CONFIG_OT_CHIP_TYPE 0x3519d500
#define CONFIG_OT_ARCH "hi3519dv500"
#define CONFIG_SUBCHIP_HI3519DV500 1
#define CONFIG_OT_SUBARCH "hi3519dv500"
#define CONFIG_OT_SUBCHIP_TYPE 0x3519d500
#define CONFIG_SMP 1
#define CONFIG_ARM_ARCH_TYPE "smp"
#define CONFIG_A55 1
#define CONFIG_CPU_TYPE "a55"
#define CONFIG_VERSION_ASIC 1
#define CONFIG_LINUX_OS 1
#define CONFIG_OS_TYPE "linux"
#define CONFIG_PHYS_ADDR_BIT_WIDTH_64 1
#define CONFIG_KERNEL_SPACE 1
#define CONFIG_DRIVER_SPACE_TYPE "kernel_space"
#define CONFIG_GCC 1
#define CONFIG_LINUX_5_10_y 1
#define CONFIG_KERNEL_VERSION "linux-5.10.y"
#define CONFIG_KERNEL_AARCH64_V01C01_LINUX_GNU 1
#define CONFIG_OT_CROSS "aarch64-v01c01-linux-gnu-"
#define CONFIG_LIBC_TYPE "glibc"
#define CONFIG_KERNEL_BIT "KERNEL_BIT_64"
#define CONFIG_USER_AARCH64_V01C01_LINUX_GNU 1
#define CONFIG_OT_CROSS_LIB "aarch64-v01c01-linux-gnu-"
#define CONFIG_USER_BIT "USER_BIT_64"
#define CONFIG_LINUX_STYLE 1
#define CONFIG_CODE_SYTLE "USE_LINUX_STYLE"
#define CONFIG_RELEASE_TYPE_RELEASE 1
#define CONFIG_OT_RLS_MODE "OT_RELEASE"

/*
 * Media Modules Setup
 */

/*
 * media audio config
 */
#define CONFIG_OT_AUDIO_SUPPORT 1
#define CONFIG_OT_ACODEC_SUPPORT 1
#define CONFIG_OT_ACODEC_VERSION "V751"
#define CONFIG_OT_ACODEC_MAX_GAIN 56
#define CONFIG_OT_ACODEC_MIN_GAIN 0
#define CONFIG_OT_ACODEC_GAIN_STEP 3
#define CONFIG_OT_ACODEC_FAST_POWER_SUPPORT 1
#define CONFIG_OT_ACODEC_DIFF_SOFT_INVERT 1
#define CONFIG_OT_DOWNVQE_SUPPORT 1
#define CONFIG_OT_TALKVQE_SUPPORT 1
#define CONFIG_OT_RECORDVQE_SUPPORT 1
#define CONFIG_OT_TALKVQEV2_SUPPORT 1
#define CONFIG_OT_TALKVQEV2_WNR_SUPPORT 1
#define CONFIG_OT_AUDIO_STATIC_REGISTER_SUPPORT 1
#define CONFIG_OT_AUDIO_DMIC_SUPPORT 1
#define CONFIG_OT_AENC_SUPPORT 1
#define CONFIG_OT_AENC_AAC_SUPPORT 1
#define CONFIG_OT_AENC_MP3_SUPPORT 1
#define CONFIG_OT_AENC_OPUS_SUPPORT 1
#define CONFIG_OT_ADEC_SUPPORT 1
#define CONFIG_OT_ADEC_AAC_SUPPORT 1
#define CONFIG_OT_ADEC_MP3_SUPPORT 1
#define CONFIG_OT_ADEC_OPUS_SUPPORT 1

/*
 * media base config
 */

/*
 * media vb config
 */
#define CONFIG_OT_VB_EXTPOOL_SUPPORT 1
#define CONFIG_OT_VB_SUPPLEMENT_MASK_SUPPORT 1

/*
 * media vca config
 */
#define CONFIG_OT_VCA_SUPPORT 1

/*
 * media chnl config
 */
#define CONFIG_OT_CHNL_SUPPORT 1

/*
 * media dis config
 */
#define CONFIG_OT_DIS_SUPPORT 1
#define CONFIG_OT_DIS_SUBMIT_TO_VGS_SUPPORT 1
#define CONFIG_OT_GYRO_DIS_MESH_SUPPORT 1

/*
 * media gdc config
 */
#define CONFIG_OT_GDC_SUPPORT 1
#define CONFIG_OT_GDC_LOWDELAY_SUPPORT 1
#define CONFIG_OT_GDC_FISHEYE_LMF_SUPPORT 1
#define CONFIG_OT_GDC_FISHEYE_SUPPORT 1
#define CONFIG_OT_GDC_LDC_SUPPORT 1
#define CONFIG_OT_GDC_LDC_V2_SUPPORT 1
#define CONFIG_OT_GDC_SPREAD_SUPPORT 1
#define CONFIG_OT_GDC_LUT_SUPPORT 1
#define CONFIG_OT_GDC_SCALE_SUPPORT 1
#define CONFIG_OT_GDC_STITCH_SUPPORT 1
#define CONFIG_OT_GDC_PRE_ROTATION_SUPPORT 1

/*
 * media hdmi config
 */

/*
 * media isp config
 */
#define CONFIG_OT_ISP_SUPPORT 1
#define CONFIG_OT_ISP_AF_SUPPORT 1
#define CONFIG_OT_ISP_CR_SUPPORT 1
#define CONFIG_OT_ISP_GCAC_SUPPORT 1
#define CONFIG_OT_ISP_CA_SUPPORT 1
#define CONFIG_OT_ISP_SPECAWB_SUPPORT 1
#define CONFIG_OT_ISP_DETAIL_STATS_SUPPORT 1
#define CONFIG_OT_ISP_DPC_STATIC_TABLE_SUPPORT 1
#define CONFIG_OT_AIISP_SUPPORT 1
#define CONFIG_OT_AIBNR_SUPPORT 1
#define CONFIG_OT_AIDRC_SUPPORT 1
#define CONFIG_OT_AIDM_SUPPORT 1
#define CONFIG_OT_AI3DNR_SUPPORT 1
#define CONFIG_OT_AIDESTRIP_SUPPORT 1
#define CONFIG_OT_NUC_SUPPORT 1

/*
 * media region config
 */
#define CONFIG_OT_REGION_SUPPORT 1
#define CONFIG_OT_RGN_VGS_QUICKCOPY_SUPPORT 1
#define CONFIG_OT_RGN_CORNER_RECT_SUPPORT 1

/*
 * media sys config
 */
#define CONFIG_OT_SYS_SUPPORT 1
#define CONFIG_OT_SYS_SCALE_COEF_SUPPORT 1
#define CONFIG_OT_SYS_3DNR_POS_SET_SUPPORT 1
#define CONFIG_OT_SYS_FMU_SUPPORT 1
#define CONFIG_OT_SYS_FMU0_SUPPORT 1
#define CONFIG_OT_SYS_FMU0_DIRECT_SUPPORT 1
#define CONFIG_OT_SYS_FMU1_SUPPORT 1
#define CONFIG_OT_SYS_FMU1_DIRECT_SUPPORT 1
#define CONFIG_OT_SYS_FMU1_WRAP_SUPPORT 1
#define CONFIG_SYS_CLK_CTRL_SUPPORT 1

/*
 * media tde config
 */
#define CONFIG_OT_TDE_SUPPORT 1

/*
 * media vda config
 */

/*
 * media vdec config
 */
#define CONFIG_OT_VDEC_SUPPORT 1
#define CONFIG_OT_H265D_SUPPORT 1
#define CONFIG_OT_H264D_SUPPORT 1
#define CONFIG_OT_JPEGD_SUPPORT 1
#define CONFIG_OT_DEC_SHVC_SUPPORT 1
#define CONFIG_VDEC_IP "VDEC_IP_VEDU"
#define CONFIG_OT_JPEGD_SUPPORT 1
#define CONFIG_OT_JPEGD_LEFT_EAR_SUPPORT 1
#define CONFIG_OT_JPEGD_PROGRESSIVE 1
#define CONFIG_OT_JPEGD_MESSAGE_POOL_SUPPORT 1
#define CONFIG_VDEC_ROTATION_SUPPORT 1
#define CONFIG_VDEC_TILE_ROTATION_SUPPORT 1
#define CONFIG_VDEC_LOW_DELAY_ROTATION_SUPPORT 1
#define CONFIG_VDEC_USERDATA_SUPPORT 1
#define CONFIG_VDEC_LOWDELAY_SUPPORT 1

/*
 * media venc config
 */
#define CONFIG_OT_VENC_SUPPORT 1
#define CONFIG_OT_VENC_KERNEL_VERSION 1
#define CONFIG_OT_H265E_SUPPORT 1
#define CONFIG_OT_H265E_USERDATA_SUPPORT 1
#define CONFIG_OT_H265E_INTRA_REFRESH_SUPPORT 1
#define CONFIG_OT_H264E_SUPPORT 1
#define CONFIG_OT_H264E_USERDATA_SUPPORT 1
#define CONFIG_OT_H264E_INTRA_REFRESH_SUPPORT 1
#define CONFIG_OT_JPEGE_SUPPORT 1
#define CONFIG_OT_JPEGE_ROI_SUPPORT 1
#define CONFIG_OT_MJPEGE_SUPPORT 1
#define CONFIG_OT_JPEGE_MPF_DCF_SUPPORT 1
#define CONFIG_OT_JPEGE_USERDATA_SUPPORT 1
#define CONFIG_OT_VENC_LOWDELAY_SUPPORT 1
#define CONFIG_OT_VENC_VPSSAUTO_SUPPORT 1
#define CONFIG_OT_VENC_FRAMEBUF_RECYCLE_SUPPORT 1
#define CONFIG_OT_VENC_VGS_SUPPORT 1
#define CONFIG_OT_VENC_SVC_SUPPORT 1
#define CONFIG_OT_VENC_SMARTP_SUPPORT 1
#define CONFIG_OT_VENC_DUALP_SUPPORT 1
#define CONFIG_OT_VENC_RCNREF_SHARE_SUPPORT 1
#define CONFIG_OT_VENC_DEBREATH_SUPPORT 1
#define CONFIG_OT_VENC_SKIPREF_SUPPORT 1
#define CONFIG_OT_VENC_SCENE0_SUPPORT 1
#define CONFIG_OT_VENC_SCENE1_SUPPORT 1
#define CONFIG_OT_VENC_SCENE2_SUPPORT 1
#define CONFIG_OT_RC_AVBR_SUPPORT 1
#define CONFIG_OT_RC_QPMAP_SUPPORT 1
#define CONFIG_OT_RC_QVBR_SUPPORT 1
#define CONFIG_OT_RC_CVBR_SUPPORT 1
#define CONFIG_OT_VENC_COMPOSITE_SUPPORT 1

/*
 * media vgs config
 */
#define CONFIG_OT_VGS_SUPPORT 1
#define CONFIG_OT_VGS_STITCH_SUPPORT 1
#define CONFIG_OT_VGS_LUMA_STAT_SUPPORT 1
#define CONFIG_OT_VGS_CORNER_RECT_SUPPORT 1
#define CONFIG_OT_VGS_SHBD_SUPPORT 1
#define CONFIG_OT_VGS_MCF_SUPPORT 1
#define CONFIG_OT_VGS_LOW_DELAY_SUPPORT 1
#define CONFIG_OT_VGS_ROTATION_INPUT_LOW_DELAY_SUPPORT 1
#define CONFIG_OT_VGS_FPD_SUPPORT 1
#define CONFIG_OT_VGS_MULTI_CHN_SUPPORT 1
#define CONFIG_OT_VGS_GME_SUPPORT 1
#define CONFIG_OT_VGS_MOSAIC_ONLINE_SUPPORT 1
#define CONFIG_OT_VGS_HOR_CHROMA_8TAP_SCALE_COEF_SUPPORT 1
#define CONFIG_OT_VGS_BLEND_SUPPORT 1

/*
 * media vi config
 */
#define CONFIG_OT_VI_SUPPORT 1
#define CONFIG_OT_VI_ALL_SUPPORT 1
#define CONFIG_OT_VI_DEV_SEND_FRAME 1
#define CONFIG_OT_VI_DEV_GENERATE_TIMING 1
#define CONFIG_OT_VI_DEV_GENERATE_DATA 1
#define CONFIG_OT_VI_VIRT_PIPE 1
#define CONFIG_OT_VI_PIPE_PRE_CROP 1
#define CONFIG_OT_VI_PIPE_POST_CROP 1
#define CONFIG_OT_VI_PIPE_DUMP_FRAME 1
#define CONFIG_OT_VI_PIPE_DUMP_PRIVATE_DATA 1
#define CONFIG_OT_VI_PIPE_SEND_FRAME 1
#define CONFIG_OT_VI_PIPE_INTERRUPT_EN 1
#define CONFIG_OT_VI_PIPE_LOW_DELAY 1
#define CONFIG_OT_VI_PIPE_FRAME_INTERRUPT_TYPE 1
#define CONFIG_OT_VI_PIPE_GET_COMPRESS_PARAM 1
#define CONFIG_OT_VI_PIPE_USER_PIC 1
#define CONFIG_OT_VI_PIPE_FPN 1
#define CONFIG_OT_VI_PIPE_IR_ASSIST_NR 1
#define CONFIG_OT_VI_PIPE_BNR 1
#define CONFIG_OT_VI_PIPE_VNR 1
#define CONFIG_OT_VI_CHN_LOW_DELAY 1
#define CONFIG_OT_VI_CHN_DIS 1
#define CONFIG_OT_VI_STITCH_GRP 1
#define CONFIG_OT_VI_PTS 1
#define CONFIG_OT_VI_VIRT_IP 1
#define CONFIG_OT_VI_PIPE_RGBW 1

/*
 * media vo config
 */
#define CONFIG_OT_VO_SUPPORT 1
#define CONFIG_OT_VO_VPSS_AUTO 1
#define CONFIG_OT_VO_PLAY_CTL 1
#define CONFIG_OT_VO_COVER_OSD_SUPPORT 1
#define CONFIG_OT_VO_CORNER_RECT_SUPPORT 1
#define CONFIG_OT_VO_VGS 1
#define CONFIG_OT_VO_GRAPH 1
#define CONFIG_OT_VO_LOW_DELAY 1
#define CONFIG_OT_VO_BORDER_BY_COVER 1
#define CONFIG_OT_VO_RGB 1
#define CONFIG_OT_VO_BT1120 1
#define CONFIG_OT_VO_MIPI 1
#define CONFIG_OT_VO_INTF_GAMMA 1
#define CONFIG_OT_VO_LESS_BUF 1
#define CONFIG_OT_VO_USER_NOTIFY 1
#define CONFIG_OT_VO_DEV_BYPASS 1
#define CONFIG_OT_VO_LAYER_HOR_HALF_SPLIT_SUPPORT 1
#define CONFIG_OT_VO_CHN_ASPECT_RATIO 1
#define CONFIG_OT_VO_EXPORT_FUNCTION 1
#define CONFIG_OT_VO_FB_SEPARATE 1

/*
 * media vpss config
 */
#define CONFIG_OT_VPSS_SUPPORT 1

/*
 * vpss online config
 */
#define CONFIG_OT_VPSS_VIPROC_VPSS_ONLINE_SUPPORT 1
#define CONFIG_OT_VPSS_ONLINE_SUPPORT 1

/*
 * vpss 3dnr config
 */
#define CONFIG_OT_VPSS_3DNR_SUPPORT 1
#define CONFIG_OT_VPSS_3DNR_GAMMA_SUPPORT 1
#define CONFIG_OT_VPSS_AUTO_SUPPORT 1

/*
 * vpss rgn config
 */

/*
 * vpss grp rgn config
 */
#define CONFIG_OT_VPSS_CORNER_RECT_SUPPORT 1
#define CONFIG_OT_VPSS_MOSAIC_SUPPORT 1

/*
 * vpss chn rgn config
 */
#define CONFIG_OT_VPSS_RGN_ON_CHN_SUPPORT 1
#define CONFIG_OT_VPSS_COVER_SUPPORT 1
#define CONFIG_OT_VPSS_COVER_RECT_SUPPORT 1
#define CONFIG_OT_VPSS_COVER_HOLLOW_SUPPORT 1
#define CONFIG_OT_VPSS_2SCALE_SUPPORT 1
#define CONFIG_OT_VPSS_VGS_GRP_SUPPORT 1
#define CONFIG_OT_VPSS_BUFFER_REUSE_SUPPORT 1
#define CONFIG_OT_VPSS_LOW_DELAY_SUPPORT 1
#define CONFIG_OT_VPSS_EXT_CHN_SUPPORT 1
#define CONFIG_OT_VPSS_CHN_CROP_SUPPORT 1
#define CONFIG_OT_VPSS_GRP_CROP_SIZE_PRIOR_SUPPORT 1
#define CONFIG_OT_VPSS_CHN_STRIDE_ALIGN_SUPPORT 1
#define CONFIG_OT_VPSS_CHN_LBA_SUPPORT 1
#define CONFIG_OT_VPSS_MCF_SUPPORT 1

/*
 * vpss gdc config
 */
#define CONFIG_OT_VPSS_GDC_SUPPORT 1
#define CONFIG_OT_VPSS_FISHEYE_LMF_SUPPORT 1

/*
 * vpss grp gdc config
 */
#define CONFIG_OT_VPSS_GRP_GDC_SUPPORT 1
#define CONFIG_OT_VPSS_OUT_LUT_SUPPORT 1
#define CONFIG_OT_VPSS_GRP_LDC_SUPPORT 1
#define CONFIG_OT_VPSS_GRP_SPREAD_SUPPORT 1
#define CONFIG_OT_VPSS_GRP_FISHEYE_SUPPORT 1
#define CONFIG_OT_VPSS_GRP_ROTATION_SUPPORT 1
#define CONFIG_OT_VPSS_GRP_PMF_SUPPORT 1
#define CONFIG_OT_VPSS_GRP_FOV_SUPPORT 1
#define CONFIG_OT_VPSS_GRP_LUT_SUPPORT 1
#define CONFIG_OT_VPSS_GRP_ZME_SUPPORT 1
#define CONFIG_OT_VPSS_GRP_STITCH_SUPPORT 1
#define CONFIG_OT_VPSS_GRP_STITCH_BLEND_SUPPORT 1

/*
 * vpss chn gdc config
 */
#define CONFIG_OT_VPSS_NODE_CANCEL_SUPPORT 1

/*
 * media vpp config
 */
#define CONFIG_OT_VPP_SUPPORT 1
#define CONFIG_OT_VPP_FOV_CORRECTION_SUPPORT 1
#define CONFIG_OT_VPP_VI_SUPPORT 1
#define CONFIG_OT_VPP_COVEREX_RATIO_SUPPORT 1
#define CONFIG_OT_VPP_GRP_GDC_SUPPORT 1
#define CONFIG_OT_VPP_STITCH_SUPPORT 1
#define CONFIG_OT_VPP_PMF_SUPPORT 1

/*
 * media dcc config
 */

/*
 * media security_subsys Config
 */
#define CONFIG_OT_SECURITY_SUBSYS_SUPPORT 1
#define CONFIG_OT_CIPHER_SUPPORT 1

/*
 * media gfbg Config
 */
#define CONFIG_OT_GFBG_SUPPORT 1
#define CONFIG_GFBG_DPU_V3 1

/*
 * media ot_syslink Config
 */

/*
 * media pciv Config
 */

/*
 * media avs lut Config
 */
#define CONFIG_OT_AVS_LUT_SUPPORT 1

/*
 * media avs convert Config
 */

/*
 * media pos_query Config
 */

/*
 * media snap Config
 */
#define CONFIG_OT_SNAP_SUPPORT 1

/*
 * media photo Config
 */

/*
 * media heif Config
 */
#define CONFIG_OT_HEIF_SUPPORT 1

/*
 * media svp Config
 */
#define CONFIG_OT_SVP_SUPPORT 1
#define CONFIG_OT_SVP_IVE 1
#define CONFIG_OT_SVP_IVE_CSC 1
#define CONFIG_OT_SVP_IVE_FILTER_AND_CSC 1
#define CONFIG_OT_SVP_IVE_NCC 1
#define CONFIG_OT_SVP_IVE_LBP 1
#define CONFIG_OT_SVP_IVE_NORM_GRAD 1
#define CONFIG_OT_SVP_IVE_ST_CANDI_CORNER 1
#define CONFIG_OT_SVP_IVE_RESIZE 1
#define CONFIG_OT_SVP_IVE_PERSP_TRANS 1
#define CONFIG_OT_SVP_IVE_KCF 1
#define CONFIG_OT_SVP_IVE_HOG 1
#define CONFIG_OT_SVP_MD 1
#define CONFIG_OT_SVP_NPU_V2R2 1
#define CONFIG_OT_SVP_DPU_RECT 1
#define CONFIG_OT_SVP_DPU_MATCH 1

/*
 * media motionfusion config
 */
#define CONFIG_OT_MOTIONFUSION_SUPPORT 1

/*
 * media mcf Config
 */
#define CONFIG_OT_MCF_SUPPORT 1

/*
 * media securec Config
 */
#define CONFIG_OT_SECUREC_SUPPORT 1

/*
 * media irq config
 */

/*
 * media proc config
 */

/*
 * media uvc config
 */
#define CONFIG_OT_UVC_SUPPORT 1

/*
 * media smmz agent config
 */
#define CONFIG_OT_SMMZ_AGENT_SUPPORT 1

/*
 * media pm Config
 */
#define CONFIG_OT_PM_SUPPORT 1
#define CONFIG_OT_PM_TEMP_COMP_SUPPORT 1

/*
 * Device Driver Setup
 */

/*
 * drv config
 */
#define CONFIG_DRV 1
#define CONFIG_EXTDRV 1
#define CONFIG_INTERDRV 1
#define CONFIG_OT_USER 1
#define CONFIG_MIPI_TX 1
#define CONFIG_MIPI_RX 1
#define CONFIG_OT_ADC 1
#define CONFIG_OT_LSADC 1
#define CONFIG_OT_WDG 1
#define CONFIG_OT_SYSCFG 1

/*
 * Debug Config
 */

/*
 * GDB  config
 */
#define CONFIG_OT_GDB_NO 1
#define CONFIG_OT_GDB "n"
#define CONFIG_OT_PROC_SHOW_SUPPORT 1
#define CONFIG_OT_LOG_TRACE_SUPPORT 1
#define CONFIG_OT_LOG_TRACE_ALL 1
#define CONFIG_OT_LOG_TRACE_LEVEL 7

#endif /* __AUTOCONF_H__ */

