/*
  Copyright (c), 2001-2022, Shenshu Tech. Co., Ltd.
 */

#ifndef HI_ERRNO_H
#define HI_ERRNO_H

#include "hi_debug.h"
#include "ot_errno.h"

#ifdef __cplusplus
extern "C" {
#endif

#define HI_ERR_APP_ID OT_ERR_APP_ID
#define HI_DEFINE_ERR OT_DEFINE_ERR
#define HI_ERR_LEVEL_DEBUG OT_ERR_LEVEL_DEBUG
#define HI_ERR_LEVEL_INFO OT_ERR_LEVEL_INFO
#define HI_ERR_LEVEL_NOTICE OT_ERR_LEVEL_NOTICE
#define HI_ERR_LEVEL_WARNING OT_ERR_LEVEL_WARNING
#define HI_ERR_LEVEL_ERROR OT_ERR_LEVEL_ERROR
#define HI_ERR_LEVEL_CRIT OT_ERR_LEVEL_CRIT
#define HI_ERR_LEVEL_ALERT OT_ERR_LEVEL_ALERT
#define HI_ERR_LEVEL_FATAL OT_ERR_LEVEL_FATAL
#define HI_ERR_LEVEL_BUTT OT_ERR_LEVEL_BUTT
typedef ot_err_level hi_err_level;
#define HI_ERR_INVALID_DEV_ID OT_ERR_INVALID_DEV_ID
#define HI_ERR_INVALID_PIPE_ID OT_ERR_INVALID_PIPE_ID
#define HI_ERR_INVALID_CHN_ID OT_ERR_INVALID_CHN_ID
#define HI_ERR_INVALID_LAYER_ID OT_ERR_INVALID_LAYER_ID
#define HI_ERR_INVALID_GRP_ID OT_ERR_INVALID_GRP_ID
#define HI_ERR_ILLEGAL_PARAM OT_ERR_ILLEGAL_PARAM
#define HI_ERR_EXIST OT_ERR_EXIST
#define HI_ERR_UNEXIST OT_ERR_UNEXIST
#define HI_ERR_NULL_PTR OT_ERR_NULL_PTR
#define HI_ERR_NOT_CFG OT_ERR_NOT_CFG
#define HI_ERR_NOT_SUPPORT OT_ERR_NOT_SUPPORT
#define HI_ERR_NOT_PERM OT_ERR_NOT_PERM
#define HI_ERR_NOT_ENABLE OT_ERR_NOT_ENABLE
#define HI_ERR_NOT_DISABLE OT_ERR_NOT_DISABLE
#define HI_ERR_NOT_START OT_ERR_NOT_START
#define HI_ERR_NOT_STOP OT_ERR_NOT_STOP
#define HI_ERR_NO_MEM OT_ERR_NO_MEM
#define HI_ERR_NO_BUF OT_ERR_NO_BUF
#define HI_ERR_BUF_EMPTY OT_ERR_BUF_EMPTY
#define HI_ERR_BUF_FULL OT_ERR_BUF_FULL
#define HI_ERR_NOT_READY OT_ERR_NOT_READY
#define HI_ERR_TIMEOUT OT_ERR_TIMEOUT
#define HI_ERR_BAD_ADDR OT_ERR_BAD_ADDR
#define HI_ERR_BUSY OT_ERR_BUSY
#define HI_ERR_SIZE_NOT_ENOUGH OT_ERR_SIZE_NOT_ENOUGH
#define HI_ERR_NOT_BINDED OT_ERR_NOT_BINDED
#define HI_ERR_BINDED OT_ERR_BINDED
#define HI_ERR_BUTT OT_ERR_BUTT
typedef ot_errno hi_errno;

#ifdef __cplusplus
}
#endif
#endif /* HI_ERRNO_H */
