#undef STRUCT
#undef STRING
#undef FIELD
#undef ARRAY
#undef BINARY
#undef ARRAY2
#undef ARRAY3
#undef string
#undef uint64
#undef uint32
#undef uint16
#undef uint8
#undef UNION_B
#undef UNION_C
#undef UNION_S
#undef UNION_E
